//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public int idAddress { get; set; }
        public string street { get; set; }
        public string number { get; set; }
        public string city { get; set; }
        public string zipcode { get; set; }
        public string neighborhood { get; set; }
        public string instructions { get; set; }
        public int idCustomer { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
