//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class dailyBalance
    {
        public int idDailyBalance { get; set; }
        public string date { get; set; }
        public double totalMoney { get; set; }
        public string idWorker { get; set; }
        public int idCashbox { get; set; }
    
        public virtual cashbox cashbox { get; set; }
        public virtual cashbox cashbox1 { get; set; }
        public virtual worker worker { get; set; }
        public virtual worker worker1 { get; set; }
    }
}
