//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class dailyBalance
    {
        public int idDailyBalance { get; set; }
        public string date { get; set; }
        public double totalMoney { get; set; }
        public string idWorker { get; set; }
        public int idCashbox { get; set; }
    
        public virtual cashbox cashbox { get; set; }
        public virtual worker worker { get; set; }
    }
}
