//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class deliveryOrder
    {
        public int idDeliveryOrder { get; set; }
        public int idOrder { get; set; }
        public int idCustomer { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual customer customer1 { get; set; }
        public virtual orders orders { get; set; }
        public virtual orders orders1 { get; set; }
    }
}
