//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplierIngredient
    {
        public int idSupplierIngredient { get; set; }
        public string idSupplierOrder { get; set; }
        public int idIngredient { get; set; }
        public int quantity { get; set; }
    
        public virtual ingredient ingredient { get; set; }
        public virtual supplierOrder supplierOrder { get; set; }
    }
}
