//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplierIngredient
    {
        public string idSupplierOrder { get; set; }
        public int idIngredient { get; set; }
        public double quantity { get; set; }
    
        public virtual ingredient ingredient { get; set; }
        public virtual supplierOrder supplierOrder { get; set; }
    }
}
