//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public int idSupplier { get; set; }
        public string supplierAddress { get; set; }
        public string email { get; set; }
        public string phoneNumber { get; set; }
        public string rfc { get; set; }
        public string supplierType { get; set; }
        public string supplierName { get; set; }
        public bool active { get; set; }
    }
}
