//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("View.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap addPizza {
            get {
                object obj = ResourceManager.GetObject("addPizza", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Global_Cancel_Button {
            get {
                return ResourceManager.GetString("Global_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario..
        /// </summary>
        public static string Global_Username_Label {
            get {
                return ResourceManager.GetString("Global_Username_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese su contraseña.
        /// </summary>
        public static string Login_ContentPasswordBox_Label {
            get {
                return ResourceManager.GetString("Login_ContentPasswordBox_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ej. paco18.
        /// </summary>
        public static string Login_ContentTextBox_Label {
            get {
                return ResourceManager.GetString("Login_ContentTextBox_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidaste tu contraseña?, consúltalo con tu administrador.
        /// </summary>
        public static string Login_ForgotPasswordInfo_Login {
            get {
                return ResourceManager.GetString("Login_ForgotPasswordInfo_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesion.
        /// </summary>
        public static string Login_Login_Button {
            get {
                return ResourceManager.GetString("Login_Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de sesión.
        /// </summary>
        public static string Login_Login_Tittle {
            get {
                return ResourceManager.GetString("Login_Login_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña..
        /// </summary>
        public static string Login_Password_Label {
            get {
                return ResourceManager.GetString("Login_Password_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string UserRegister_Address_Label {
            get {
                return ResourceManager.GetString("UserRegister_Address_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        public static string UserRegister_Administrator_WorkerType {
            get {
                return ResourceManager.GetString("UserRegister_Administrator_WorkerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cajero.
        /// </summary>
        public static string UserRegister_Cashier_WorkerType {
            get {
                return ResourceManager.GetString("UserRegister_Cashier_WorkerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad:.
        /// </summary>
        public static string UserRegister_City_Label {
            get {
                return ResourceManager.GetString("UserRegister_City_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonia:.
        /// </summary>
        public static string UserRegister_Colony_Label {
            get {
                return ResourceManager.GetString("UserRegister_Colony_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocinero.
        /// </summary>
        public static string UserRegister_Cook_WorkerType {
            get {
                return ResourceManager.GetString("UserRegister_Cook_WorkerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string UserRegister_Customer_UserType {
            get {
                return ResourceManager.GetString("UserRegister_Customer_UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente registrado con éxito.
        /// </summary>
        public static string UserRegister_CustomerSuccesfull_Message {
            get {
                return ResourceManager.GetString("UserRegister_CustomerSuccesfull_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico:.
        /// </summary>
        public static string UserRegister_Email_Label {
            get {
                return ResourceManager.GetString("UserRegister_Email_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido:.
        /// </summary>
        public static string UserRegister_LastName_Label {
            get {
                return ResourceManager.GetString("UserRegister_LastName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre:.
        /// </summary>
        public static string UserRegister_Name_Label {
            get {
                return ResourceManager.GetString("UserRegister_Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de seguro social (NSS): .
        /// </summary>
        public static string UserRegister_NSS_Label {
            get {
                return ResourceManager.GetString("UserRegister_NSS_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número exterior:.
        /// </summary>
        public static string UserRegister_Number_Label {
            get {
                return ResourceManager.GetString("UserRegister_Number_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña:.
        /// </summary>
        public static string UserRegister_Password_Label {
            get {
                return ResourceManager.GetString("UserRegister_Password_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono:.
        /// </summary>
        public static string UserRegister_PhoneNumber_Label {
            get {
                return ResourceManager.GetString("UserRegister_PhoneNumber_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referencias:.
        /// </summary>
        public static string UserRegister_References_Label {
            get {
                return ResourceManager.GetString("UserRegister_References_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar.
        /// </summary>
        public static string UserRegister_Register_Button {
            get {
                return ResourceManager.GetString("UserRegister_Register_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC:.
        /// </summary>
        public static string UserRegister_RFC_Label {
            get {
                return ResourceManager.GetString("UserRegister_RFC_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calle:.
        /// </summary>
        public static string UserRegister_Street_Label {
            get {
                return ResourceManager.GetString("UserRegister_Street_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string UserRegister_Supervisor_WorkerType {
            get {
                return ResourceManager.GetString("UserRegister_Supervisor_WorkerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de Usuario.
        /// </summary>
        public static string UserRegister_Title_Label {
            get {
                return ResourceManager.GetString("UserRegister_Title_Label", resourceCulture);
            }
        }

		/// <summary>
		///   Looks up a localized string similar to Nombre de usuario:.
		/// </summary>
		public static string UserRegister_Username_Label {
            get {
                return ResourceManager.GetString("UserRegister_Username_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de usuario:.
        /// </summary>
        public static string UserRegister_UserType_Label {
            get {
                return ResourceManager.GetString("UserRegister_UserType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesero.
        /// </summary>
        public static string UserRegister_Waiter_WorkerType {
            get {
                return ResourceManager.GetString("UserRegister_Waiter_WorkerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajador.
        /// </summary>
        public static string UserRegister_Worker_UserType {
            get {
                return ResourceManager.GetString("UserRegister_Worker_UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos del Trabajador.
        /// </summary>
        public static string UserRegister_WorkerData_Label {
            get {
                return ResourceManager.GetString("UserRegister_WorkerData_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de trabajador:.
        /// </summary>
        public static string UserRegister_WorkerNumber_Label {
            get {
                return ResourceManager.GetString("UserRegister_WorkerNumber_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajador registrado con éxito.
        /// </summary>
        public static string UserRegister_WorkerSuccesfull_Message {
            get {
                return ResourceManager.GetString("UserRegister_WorkerSuccesfull_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de trabajador:.
        /// </summary>
        public static string UserRegister_WorkerType_Label {
            get {
                return ResourceManager.GetString("UserRegister_WorkerType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código postal:.
        /// </summary>
        public static string UserRegister_ZipCode_Label {
            get {
                return ResourceManager.GetString("UserRegister_ZipCode_Label", resourceCulture);
            }
        }
    }
}
